### ISSUE TITLE
AttributeError: 'module' object has no attribute 'chain_cmd'

### ISSUE THREAD

**Issue by fbemm** [jasperlinthorst/reveal#14]
I am trying to get the latest commit to work and initially got the following:

```
Traceback (most recent call last):
  File "./env/bin/reveal", line 11, in <module>
    load_entry_point('reveal==0.1', 'console_scripts', 'reveal')()
  File "/ebio/abt6_projects9/abt6_software/bin/reveal/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/ebio/abt6_projects9/abt6_software/bin/reveal/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/ebio/abt6_projects9/abt6_software/bin/reveal/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/ebio/abt6_projects9/abt6_software/bin/reveal/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/reveal/reveal.py", line 25, in <module>
ImportError: No module named chain
```

I did install chain with 

`pip install chain`

but I am not sure it is the right version or even the right package. 

```
Traceback (most recent call last):
  File "./env/bin/reveal", line 11, in <module>
    load_entry_point('reveal==0.1', 'console_scripts', 'reveal')()
  File "build/bdist.linux-x86_64/egg/reveal/reveal.py", line 168, in main
AttributeError: 'module' object has no attribute 'chain_cmd'
```

This is what is getting installed:

```
pip show chain
Name: chain
Version: 1.0
Summary: A jQuery like list wrapper.
Home-page: UNKNOWN
Author: Hao Deng
Author-email: denghao8888@gmail.co
```

**Comment by jasperlinthorst** [comment]
Sorry about that, I forgot to push the chain module to github. If you do a new pull and reinstall it should be fixed.. Thanks for pointing it out!
