### ISSUE TITLE
reveal realign - muscle fails

### ISSUE THREAD

**Issue by ChriKub** [jasperlinthorst/reveal#26]
Hi,
I'm using reveal realign with muscle to realign bubbles in a graph.
`reveal realign --64 --method muscle --all --maxsize 5000 -o $output $input`
At some point during the realignment it fails:
`10/03/2018 01:04:06 PM Realigning bubble between <431323> and <99201>, 2 alleles, with muscle (max size 10bp, in nodes=2).
Traceback (most recent call last):
  File "/ebio/abt6_projects9/abt6_software/bin/reveal/env/bin/reveal", line 11, in <module>
    load_entry_point('reveal==0.1', 'console_scripts', 'reveal')()
  File "build/bdist.linux-x86_64/egg/reveal/reveal.py", line 294, in main
  File "build/bdist.linux-x86_64/egg/reveal/refine.py", line 44, in refine_bubble_cmd
  File "build/bdist.linux-x86_64/egg/reveal/refine.py", line 413, in refine_all
  File "build/bdist.linux-x86_64/egg/reveal/refine.py", line 206, in refine_bubble
  File "build/bdist.linux-x86_64/egg/reveal/refine.py", line 483, in msa2graph
AttributeError: 'exceptions.OSError' object has no attribute 'output'`

I've observed this behavior in different graphs with different maxsizes. and I'm not sure how this happens.

Cheers,
Christian

**Comment by jasperlinthorst** [comment]
Hi Christian,
For some reason subprocess raises an OSError while attempting to call
'muscle'. This exception isn't handled properly at the moment, which is
something that I will fix.
I can't really tell you why this OSError is raised, but I suspect that it
has something to do with the fact that the exact command, something along
the lines of: "muscle -in <tmpfile>.fasta -quiet" on the concerning machine
cannot the executed properly by the OS.
As I think that this has something to do with your system configuration,
it's a bit hard for me to help out with.

Good luck and let me know,
Jasper
