### ISSUE TITLE
reveal rem error

### ISSUE THREAD

**Issue by Bobo22331** [jasperlinthorst/reveal#33]
Hi,

When I run reveal of 24 genomes using:
```
$REVEAL rem --64 -t $THREADS  data/westar.fa data/kale.gfa data/LT.gfa data/mendel.gfa data/FAFU-ZS11.gfa data/Express617.gfa data/HZAU-ganganF73.gfa data/HZAU-no2127.gfa data/HZAU-quintaA.gfa data/HZAU-shengli3.gfa data/HZAU-tapidor3.gfa data/HZAU-westar.gfa data/HZAU-zheyou73.gfa data/HZAU-zs11.gfa data/NY7.gfa data/darmor.gfa data/ZS11.gfa data/tapidor.gfa data/TH008A.gfa data/TH026.gfa data/TH058.gfa data/TH271.gfa data/TH430A.gfa data/TH433A.gfa data/TH435.gfa -m20  -o genomes.24.gfa
```

But it occurs the following error:
```
07/24/2020 07:57:43 PM ERROR: Graph already contains path for: *chrA06
Traceback (most recent call last):
  File "/home/cuixb/tools/biosoft/Python-2.7.18/bin/reveal", line 8, in <module>
    sys.exit(main())
  File "/home/cuixb/tools/biosoft/Python-2.7.18/lib/python2.7/site-packages/reveal/reveal.py", line 392, in main
    args.func(args)
  File "/home/cuixb/tools/biosoft/Python-2.7.18/lib/python2.7/site-packages/reveal/unzip.py", line 14, in unzip
    utils.read_gfa(args.graph[0], None, None, G, remap=False)
  File "/home/cuixb/tools/biosoft/Python-2.7.18/lib/python2.7/site-packages/reveal/utils.py", line 372, in read_gfa
    f=open(gfafile,'r')
```

So, how to solve this error?

Thank you in advance!

**Comment by jasperlinthorst** [comment]
Hi,
Path names in the gfa files that you’re trying to anchor need to be unique.
I guess that that is where the error comes from.
The *-prefixed paths are the paths that correspond to the original layout
of the assemblies, these paths should enable you to keep track of
inversions/rearrangements. If you want to only inspect colinear variation,
or just to keep track of whats happening, you might want to use ‘reveal
split’ with the —no-cycles option after the transform step and before
applying the rem anchoring approach.

Good luck,
Jasper

**Comment by Chipcui** [comment]
Thank you for your quickly reply and your suggestion. I will try to rename the sequences in my genome files and rerun the reveal.-------- 原始邮件 --------发件人： Jasper Linthorst <notifications@github.com>日期： 2020年7月24日周五 晚上9:50收件人： jasperlinthorst/reveal <reveal@noreply.github.com>抄送： XiaoboCui <cuixiaobo0223@foxmail.com>, Author <author@noreply.github.com>主    题： Re: [jasperlinthorst/reveal] reveal rem error (#33)

Hi,

Path names in the gfa files that you’re trying to anchor need to be unique.

I guess that that is where the error comes from.

The *-prefixed paths are the paths that correspond to the original layout

of the assemblies, these paths should enable you to keep track of

inversions/rearrangements. If you want to only inspect colinear variation,

or just to keep track of whats happening, you might want to use ‘reveal

split’ with the —no-cycles option after the transform step and before

applying the rem anchoring approach.



Good luck,

Jasper
